language: scala

scala:
  - 2.11.11

script:
  - sbt clean scripted scalafmt headerCheck
  - "git diff --exit-code || (echo ERROR: Git changes detected, please regenerate the readme and run scalafmt with: sbt headerCreate scalafmt && exit 1)"
#after_success:
#  - sbt coveralls
#  - bash <(curl -s https://codecov.io/bash)
