package nl.biopet.bioconda

import nl.biopet.bioconda.BiocondaPlugin.autoImport._
import sbt.Def
import sbt.Keys._

object BiocondaDefaults {
  def defaultSummary: Def.Initialize[String] =
    Def.setting {
      s"""This summary for ${(name in Bioconda).value} is automatically generated.
         |Please visit ${(homepage in Bioconda).value.getOrElse("the project's website")}
         |for more information about this program.
       """.stripMargin.replace("\n"," ")
    }

  def defaultNotes: Def.Initialize[String] =
    Def.setting {
      def javaOpts: String = {
        val javaDefaults = biocondaDefaultJavaOptions.value
        val builder = new StringBuilder
        javaDefaults.foreach(x => builder.append(x + " "))
        val opts = builder.toString().trim
        if (javaDefaults.isEmpty) "no default java option"
        else opts
      }
      s"""${(name in Bioconda).value} is Java program that comes with a custom wrapper shell script.
         |By default “$javaOpts” is set in the wrapper.
         |The command that runs the program is "${biocondaCommand.value}."
         |If you want to overwrite it you can specify memory options directly after your binaries.
         |If you have _JAVA_OPTIONS set globally this will take precedence.
         |For example run it with “${biocondaCommand.value} -Xms512m -Xmx1g”.
       """.stripMargin.replace("\n"," ")
    }
  def defaultPullRequestTitle: Def.Initialize[String] =
    Def.setting {
      s"${(name in Bioconda).value}"
    }

  def defaultPullRequestBody: Def.Initialize[String] =
    Def.setting {
      s"""This pull request was automatically generated by
         |[sbt-bioconda](https://github.com/biopet/sbt-bioconda).
         |
         |Any releases of [${(name in Bioconda).value}](${(homepage in Bioconda).value}) that
         |are not in bioconda are automatically generated if the `sbt biocondaRelease` command is issued.
         |As part of this
         |process the recipes are tested using CircleCi as described
         |[here](https://bioconda.github.io/contribute-a-recipe.html#test-locally).
         |
         |# Tool summary
         |${biocondaSummary.value}
         |.""".stripMargin
    }
}
